### ISSUE TITLE
S15 Message error with [unstore_unit] empty variable

### ISSUE THREAD

**Issue by Toranks** [inferno8/wesnoth-To_Lands_Unknown#13]
Each turn there is a 25% chance that some low level units of the player's side will be captured. But if there are not enough units to capture I get an error message (even without debug mode).

https://github.com/inferno8/wesnoth-To_Lands_Unknown/blob/43fea3d0294782d48668ba23c22594660270314b/scenarios/15_Abyssal_Rebellion.cfg#L871

![imagen](https://user-images.githubusercontent.com/40789364/219528447-2f3295f7-62b9-4b66-956d-fa7c45cf4c68.png)

I suggest adding a check with {IF_VAR capture[x] not_equals $empty_var etc.

**Comment by ProditorMagnus** [comment]
captured.length check might be more reliable.
