### ISSUE TITLE
New AMLAs

### ISSUE THREAD

**Issue by Slayer95** [inferno8/wesnoth-To_Lands_Unknown#32]
Context
- 92100b280 added Ultimate Focus and Skirmisher to Rashti.
- https://github.com/inferno8/wesnoth-Era_of_Magic/commit/8a901b21 added support for fast summon. 
- TLU TODO for 2022+:
> enable custom AMLAs and summon options for Rashti(COMPLETED v3.6)

While Rashti is quite powerful after 92100b280, imo the main selling point of AMLAs is player agency, so I hope she gets some <i>options</i>, such as:
1. **Definitive Strength**: +10% "physical" damage.
2. **Definitive Magic**: +10% "magical" damage.
3. **Definitive Intellect**: -30% Max XP required for other AMLAs. (Though she's not Nomolas).
4. **Sadism**: +25% damage to enemies below 40% HP (flavor: red Rashti).
5. **Majesty**: On offense, defender retaliates with one less strike, but at least 1 (aka "Shock" from Eastern Invasion) (flavor: blue Rashti).
6. **Fast Summon**: Rashti may summon a rhami or elemental, and still move afterwards (but no longer attack).

Other possible recipients for Fast Summon include Neutral Summoner, Heavy Summoner, Summons Masters, Mehir Commander, Mehir Leader, and Last Summoner (btw, currently Last Summoner doesn't have Mehir Leader's AMLAs available, bug?). IMO, they should all get it in the campaign.

Finally, Mehir could use a few special AMLAs (i.e. not just raw numbers bonuses). I like Meditation, so I'd like to propose "Meditation II", among others. Summing up:
1. **Good at using scrolls** (Guard and later): Adds "first strike" to scroll spell.
2. **Meditation II** (Commander and later, requires "Meditation"): Further +3 XP per turn.
3. **Synchronization** (Commander and later, requires "Good at using scrolls"): Adds "first strike" to circle of destruction, but losses regeneration (harmed 'cause stayed too long in circle).
4. **Fast Summon** (Commander and later, wbu making it and synchronization exclusive branches after "Good at using scrolls"?)

**Comment by inferno8** [comment]
All these ideas are excellent in my opinion. I especially like Rashti AMLA flavors as they make her even more interesting and fun to play. Well done!
I approve this whole proposal. Feel free to implement the ideas if you want.

> currently Last Summoner doesn't have Mehir Leader's AMLAs available, bug?

It seems like it. I have to admit Mehir's AMLA system has always been a mess...
