### ISSUE TITLE
Ally leaves his keep in Defense of Saffaros

### ISSUE THREAD

**Issue by Slayer95** [inferno8/wesnoth-To_Lands_Unknown#56]
That makes Mehir's idea of sacrificing jinn pointless, since he may simply steal Dedylos' castle.

He shouldn't leave it for, at least, the first 5 turns or until Mehir reinforces the outer wall.

**Comment by inferno8** [comment]
> He shouldn't leave it for, at least, the first 5 turns or until Mehir reinforces the outer wall.

You're right. That makes sense.

**Comment by Slayer95** [comment]
The case for sacrificing jinni should also be made more compelling. Currently, Mehir is able to recall 6 units in turn 1, followed by 6 or 10 (if he moves to another keep with movement AMLA) units in turn 2. By turn 3, without sacrificing anything, the player is able get a sizable army.

So, I'd like to propose the following:

![imagen](https://user-images.githubusercontent.com/4925744/230290838-80b088a0-e170-42f2-b08e-d9b56da83ad8.png)



- Let every outer keep have exactly 2 slots for recruiting units. Then, the player will agree with Mehir that expanding the walls would be great. 
- Let Mehir start either in the west or east keep. So that he can recruit 2 units there and further 2 units in the north keep, from turn 1. After getting notice of the jinni event, the player may decide to recall a Neutral Summoner in each of those keeps if they are available. Otherwise, they will be compelled to recruit/recall jinnis.
- If the player decided to directly recruit jinnis, they will get the full expanded castle during **turn 2** at the cost of 60 gold (recall: 54 gold).
- Otherwise, if they are using NS, he may summon 2 jinni at a total of 28 gold. Should any of the NS have the Fast Summon AMLA, then they may immediately move next to the final keep, so that the jinni event is completed during **turn 3** (total: 42 gold, not counting NS which are viable combat units here). This turn, Mehir would also be able to recruit 4 units.
- Without jinni sacrifice, and following the rate of 4 units per turn, the player should acquire 20 units during **turn 5** (Dusk), which may be enough to pass the scenario (but may be not). However, if Mehir has no movement AMLA, then the player will only have 10 units on the map. It's at this time that Dedylos lends his castle to Mehir (Hard difficulty).
- Still, the turn in which Dedylos leaves his keep may be more generous in easier difficulties.

I think this would result in a rich variety of choices.

Also, regarding this scenario, Dedylos should probably be more defense-oriented, in agreement with Mehir's lines (<i>"You defend the town and I will try to prepare a counterattack.</i>"). To that end, I suggest enforcing the village ownership distribution in the image above, and an added objective of protecting Dedylos villages' from the enemy (and not taking them yourself).

**Comment by inferno8** [comment]
I really like all these ideas. With the new castle layout, sacrificing 3 jinn may seem far more beneficial than it is now + it makes the scenario more interesting to play. Same goes to village ownership. I approve these proposals.
