### ISSUE TITLE
S16: Hydras spawn algorithm has too large power variance.

### ISSUE THREAD

**Issue by Slayer95** [inferno8/wesnoth-To_Lands_Unknown#63]
Currently, each turn there is a 50% chance of spawning a Lv2 Hydra, as well as an independent 50% chance of spawning a Lv3 Hydra. This means there is a 25% chance of spawning nothing vs 25% chance of spawning them together.

Suggestion: Spawn either 1 Lv2 Hydra or 1 Lv3 Hydra per turn (at random).

**Comment by inferno8** [comment]
Approved
