### ISSUE TITLE
Status of translations

### ISSUE THREAD

**Issue by Slayer95** [inferno8/wesnoth-To_Lands_Unknown#65]
|Language              |Valid|Invalid (Fuzzy)|Empty|
|--------------------|--------|----------|-----------|
|German (de)         |492        |664        |1430        |
|Spanish (es)         |2586        |0        |0        |
|French (fr)         |1709        |427        |450        |
|Hungarian (hu)         |237        |431        |1918|
|Italian (it)         |243        |431 |1912 |
|Polish (pl)         |2418 |62        |106        |
|Russian (ru)         |270|324|1992|
|Chinese (zh_CN)         |309|500|1777|

It can be seen that there is a large amount of missing strings in German, Hungarian, Italian, Russian, and Chinese. So I'd like to propose and step forward to handle these through machine translation (i.e. no guarantee about quality. See also [Cunningham's Law](https://en.wiktionary.org/wiki/Cunningham%27s_Law)).

French and/or fuzzy strings can be updated too, if so desired.

**Comment by ProditorMagnus** [comment]
AI generated translations are probably just as forbidden as AI generated art.

**Comment by Slayer95** [comment]
> AI generated translations are probably just as forbidden as AI generated art.

I wasn't planning to use AI, though. Anyway, is the AI restriction Wesnoth or GPL policy? Yeah. I think such a restriction wouldn't apply to translations, given that the copyright ownership of the sources (i.e. english strings) is held by the campaign author. After passing through AI processing, the ownership still belongs to the author.

This is similar to how the licencing of a compiler doesn't affect in any way the licencing of the code it's used on and the program it generates.

**Comment by Slayer95** [comment]
See also
- https://meta.wikimedia.org/wiki/Wikilegal/Copyright_for_Google_Translations
- https://www.mediawiki.org/wiki/Content_translation/Machine_Translation/Google_Translate#Summary_of_our_agreement_with_Google

(My idea is precisely using Google Translate.)

**Comment by inferno8** [comment]
> I wasn't planning to use AI, though. Anyway, is the AI restriction Wesnoth or GPL policy?

AFAIK this is Wesnoth policy, at least for images. Not sure about text though.

Google translate, while constantly becoming better and better at translating, can still produce sentences of very low quality, often completely missing the original context. I'd prefer to rely on real translators doing their job, as they usually know what they are doing and (most importantly) know the context of the story. Your proposal is a quick and dirty solution (and sometimes these are the best) but here I am not sure if it is a good idea. That's my opinion.

**Comment by Slayer95** [comment]
There is a tradeoff involved between quality and accesibility of localization. IMO, it's very disruptive to read one paragraph in your native language, followed by two or three in English. I'd prefer a low quality translation over an incomplete/outdated translation ten times over. (Of course, should the translation quality turn out to be too low, I'd prefer to just read it in English.) In general, I can only wonder what kind of audience would be fine with an incomplete translation.

Most of the translation files haven't been updated for at least 5 years, and some even go back to over 10 years ago, which raises doubts over whether the translator(s) will be willing to carry on with the work. Of course, there's a chance new blood comes through. But imo (and this is where Cunningham's Law is relevant), it would be easier for contributors to fix/polish machine translation rather than build a new one basically from scratch.

Of course, so long as you agree to this, it can go forward. Otherwise, well, I don't have a particular stake in this matter.

**Comment by Slayer95** [comment]
Updated the chart with the data after #46.

But closing the issue, since it doesn't seem to be actionable per the discussion above.
